### ISSUE TITLE
Incorrect package resolving on pip install

### ISSUE THREAD

**Issue by bIbI4k0** [flask-debugtoolbar/flask-debugtoolbar#169] opened 2022-03-28 10:46 UTC
Dont install correctly this package from locally(dev-version) or PyPi(0.12.1).

**$ python3 -m pip install --no-deps -t /home/user/downloads/fdtb .**
```
Processing /home/user/downloads/flask-debugtoolbar-master
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: Flask-DebugToolbar
  Building wheel for Flask-DebugToolbar (pyproject.toml) ... done
  Created wheel for Flask-DebugToolbar: filename=Flask_DebugToolbar-0.13.dev0-py3-none-any.whl size=13947 sha256=3c9a75c9002e40c0da1c11f7a7a57f8572f9383345f0a59358290c0705c45dd4
  Stored in directory: /home/user/.cache/pip/wheels/77/a3/de/ac26c90e4c9a0e01ac3ad75807fa3b3b5b560eb9cb74391b30
Successfully built Flask-DebugToolbar
Installing collected packages: Flask-DebugToolbar
Successfully installed Flask-DebugToolbar-0.13.dev0
```

**$ ls -ls ../fdtb/**
```
4 drwxrwxr-x 2 user users 4096 мар 28 21:37 Flask_DebugToolbar-0.13.dev0.dist-info
4 drwxrwxr-x 3 user users 4096 мар 28 21:37 panels
```
Seems like package `panels` are installed, not flask_debugtoolbar which is root. 

Python 3.9

**Comment by jeffwidman** [comment] 2022-03-28 17:18
Thanks. Dupe of https://github.com/flask-debugtoolbar/flask-debugtoolbar/issues/168

**Closed by jeffwidman** 2022-03-28 17:18 UTC
